JOKE = "HaJiMiNanBeiLvDou"
SHORTER_JOKE = "dingdongji"

OLD_TIME = "2024-01-01T01:00:00.000+00:00"
NEW_TIME = "2026-01-01T01:00:00.000+00:00"

USER_ID = 123456
CURRENT_USER = {
    "data": {
        "id": str(USER_ID),
        "type": "user",
        "attributes": {
            "about": None,
            "age_verification_status": None,
            "apple_id": None,
            "can_see_nsfw": True,
            "created": OLD_TIME,
            "current_user_block_status": "none",
            "default_country_code": None,
            "discord_id": None,
            "email": f"{JOKE}@{SHORTER_JOKE}.com",
            "facebook": None,
            "facebook_id": None,
            "first_name": JOKE,
            "full_name": JOKE,
            "gender": 0,
            "google_id": None,
            "has_password": True,
            "image_url": JOKE,
            "is_deleted": False,
            "is_email_verified": True,
            "is_nuked": False,
            "is_suspended": False,
            "last_name": "",
            "social_connections": {
                "discord": None,
                "facebook": None,
                "google": None,
                "instagram": None,
                "reddit": None,
                "spotify": None,
                "spotify_open_access": None,
                "tiktok": None,
                "twitch": None,
                "twitter": None,
                "twitter2": None,
                "twitter_new_app": None,
                "vimeo": None,
                "youtube": None,
            },
            "thumb_url": JOKE,
            "twitch": None,
            "twitter": None,
            "url": f"https://www.patreon.com/user?u={USER_ID}",
            "vanity": None,
            "youtube": None,
        },
        "relationships": {
            "address": {"data": None},
            "creator": {
                "data": {"id": "17223600", "type": "user"},
                "links": {"related": "https://www.patreon.com/api/user/17223600"},
            },
            "patron": {
                "data": {"id": "181945268", "type": "user"},
                "links": {"related": "https://www.patreon.com/api/user/181945268"},
            },
            "reward": {
                "data": {"id": "7264767", "type": "reward"},
                "links": {"related": "https://www.patreon.com/api/rewards/7264767"},
            },
        },
    },
    "links": {
        "self": f"https://www.patreon.com/api/user/{USER_ID}",
    },
    "included": [
        {
            "id": "263727286",
            "type": "pledge",
            "attributes": {
                "amount_cents": 300,
                "created_at": NEW_TIME,
                "currency": "USD",
                "declined_since": None,
                "is_grandfathered": False,
                "patron_pays_fees": False,
                "pledge_cap_cents": 300,
            },
            "relationships": {
                "address": {"data": None},
                "creator": {
                    "data": {"id": "17223600", "type": "user"},
                    "links": {"related": "https://www.patreon.com/api/user/17223600"},
                },
                "patron": {
                    "data": {"id": "181945268", "type": "user"},
                    "links": {"related": "https://www.patreon.com/api/user/181945268"},
                },
                "reward": {
                    "data": {"id": "7264767", "type": "reward"},
                    "links": {"related": "https://www.patreon.com/api/rewards/7264767"},
                },
            },
        },
        {
            "id": "17223600",
            "type": "user",
            "attributes": {
                "about": "",
                "created": "2019-02-07T14:41:15.000+00:00",
                "current_user_block_status": "none",
                "facebook": None,
                "first_name": "BeastBeat",
                "full_name": "BeastBeat",
                "gender": 0,
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJ3IjoyMDB9/10.png?token-hash=YagoQp0zh7JwY4nJexT6Xy-UDXJGchD9wWISM9eUZYk%3D",
                "last_name": "",
                "social_connections": {
                    "discord": None,
                    "facebook": None,
                    "google": None,
                    "instagram": None,
                    "reddit": None,
                    "spotify": None,
                    "spotify_open_access": None,
                    "tiktok": None,
                    "twitch": None,
                    "twitter": {
                        "url": "https://twitter.com/CBoneGames",
                        "user_id": "1439740464903589888",
                    },
                    "twitter2": None,
                    "twitter_new_app": None,
                    "vimeo": None,
                    "youtube": None,
                },
                "thumb_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJ3IjoyMDB9/10.png?token-hash=YagoQp0zh7JwY4nJexT6Xy-UDXJGchD9wWISM9eUZYk%3D",
                "twitch": None,
                "twitter": None,
                "url": "https://www.patreon.com/BeastBeatGame",
                "vanity": "BeastBeatGame",
                "youtube": None,
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "3067357", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/3067357"
                    },
                }
            },
        },
        {
            "id": "7264767",
            "type": "reward",
            "attributes": {
                "amount": 300,
                "amount_cents": 300,
                "created_at": "2021-05-30T08:10:59.053+00:00",
                "currency": "USD",
                "declined_patron_count": 188,
                "description": "<ul><li><p>Project preview</p></li></ul><p><strong>                     <u>[BeastBeat]</u></strong></p><ul><li><p>[A]Patreon_Build version game</p></li></ul>",
                "discord_role_ids": ["1128899792832045056"],
                "edited_at": "2023-07-12T10:33:13.809+00:00",
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/reward/7264767/65076e6133184eb89593783118c2311d/eyJ3Ijo0MDB9/4.png?token-hash=emcoJIxL8s2iLaFyxFdI2ZBlaQLLeZsHV9vuWJWekk8%3D",
                "is_free_tier": False,
                "patron_amount_cents": 300,
                "patron_currency": "USD",
                "post_count": 40,
                "published": True,
                "published_at": "2021-12-31T14:23:37.627+00:00",
                "remaining": None,
                "requires_shipping": False,
                "title": "Brass ticket",
                "unpublished_at": None,
                "url": "https://www.patreon.com/checkout/BeastBeatGame?rid=7264767",
                "welcome_message": None,
                "welcome_message_unsafe": None,
                "welcome_video_embed": None,
                "welcome_video_url": None,
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "3067357", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/3067357"
                    },
                }
            },
        },
        {
            "id": "3067357",
            "type": "campaign",
            "attributes": {
                "avatar_photo_image_urls": {
                    "original": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJxIjoxMDAsIndlYnAiOjB9/10.png?token-hash=nrFnYO7OQ-Q4sy9EqrJQkaXJf8Faq1NhuRptxpfPsRs%3D&token-time=1782000000",
                    "default": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJ3Ijo2MjB9/10.png?token-hash=ksjM3QCgmJyO3h97hgbs2xGcN5OS464B4sht1U471EA%3D&token-time=1782000000",
                    "default_small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJ3IjozNjB9/10.png?token-hash=hGvHRdXPa08sCEuflkqDTU_7jPpAtaOlctGEVVU21lM%3D&token-time=1782000000",
                    "default_large": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJ3IjoxMDgwfQ%3D%3D/10.png?token-hash=31Nc4kijI1SIQABmj-aeIdVkgwBNDgywhkcpl24w8V8%3D&token-time=1782000000",
                    "default_blurred": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJiIjoyMCwidyI6NjIwfQ%3D%3D/10.png?token-hash=a5ug0dw3dJ-5n-zg1ovYAooywC-B7t9EQuYffIO_-2E%3D&token-time=1782000000",
                    "default_blurred_small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJiIjoyMCwidyI6MzYwfQ%3D%3D/10.png?token-hash=XCse12fkoCLuKxXRl1sMVCHzn7EoFRxElzYXHvdfksc%3D&token-time=1782000000",
                    "thumbnail": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJoIjozNjAsInciOjM2MH0%3D/10.png?token-hash=tK2lrq2y-g2I1KKw3cJtT8nZGVsfdy1Xz2lQ5jPQLaI%3D&token-time=1782000000",
                    "thumbnail_large": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJoIjoxMDgwLCJ3IjoxMDgwfQ%3D%3D/10.png?token-hash=lgjxiYe_WibbOVxaeVel_uprDBzRlggH83ZoGgVq2Vg%3D&token-time=1782000000",
                    "thumbnail_small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJoIjoxMDAsInciOjEwMH0%3D/10.png?token-hash=jZyrD_g0iBVGYBrI6-8nkU89oSoLmT8_3CPeAsDsFPw%3D&token-time=1782000000",
                },
                "avatar_photo_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/e146916d63b84adea0a6117930614e14/eyJ3Ijo2MjB9/10.png?token-hash=5b0G58lJHiZT4V_OwtDOw79GwKrWeNMY74vJfjfWzwY%3D",
                "cover_photo_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/55.jpg?token-hash=txrhTrp-7qYr5DdkXpiBY313gbFqtS2tENmVDUcZgi8%3D&token-time=1783123200",
                "cover_photo_url_sizes": {
                    "xsmall": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3Ijo2MjAsIndlIjoxfQ%3D%3D/55.jpg?token-hash=2fzT7QY439JfzzG6-jC8tu4Zy_bxrAzByD8N4f0bbT8%3D&token-time=1783123200",
                    "small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3Ijo5NjAsIndlIjoxfQ%3D%3D/55.jpg?token-hash=a5HPn1X1BxhRX0KyZSfqJcP0JY_lU-5vKjdLUKCRxKs%3D&token-time=1783123200",
                    "medium": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxMjAwLCJ3ZSI6MX0%3D/55.jpg?token-hash=JXwhjk1X4qjwRngxoSQHHgDwk-s4Q9YNFMAh9OdGENA%3D&token-time=1783123200",
                    "large": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxNjAwLCJ3ZSI6MX0%3D/55.jpg?token-hash=0py_sSq-Ls3xb1HcdVENSNU1zoL4V7WG2BKE35l4EpU%3D&token-time=1783123200",
                    "xlarge": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/55.jpg?token-hash=txrhTrp-7qYr5DdkXpiBY313gbFqtS2tENmVDUcZgi8%3D&token-time=1783123200",
                    "low_quality": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJiIjo1MCwicSI6MSwidyI6NjIwLCJ3ZSI6MX0%3D/55.jpg?token-hash=NwtWKUn2MP-OjOt4qRaZ4gM48KSgQOQuHXdWY-kNdno%3D&token-time=1783123200",
                },
                "created_at": "2019-08-16T04:31:44.000+00:00",
                "creation_count": 222,
                "creation_name": "Furry NSFW Games & Animation",
                "currency": "USD",
                "discord_server_id": "779496383521751060",
                "display_patron_goals": False,
                "earnings_visibility": "private",
                "image_small_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/55.jpg?token-hash=txrhTrp-7qYr5DdkXpiBY313gbFqtS2tENmVDUcZgi8%3D&token-time=1783123200",
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/55.jpg?token-hash=txrhTrp-7qYr5DdkXpiBY313gbFqtS2tENmVDUcZgi8%3D&token-time=1783123200",
                "is_charge_upfront": True,
                "is_charged_immediately": True,
                "is_monthly": True,
                "is_new_fandom": False,
                "is_nsfw": True,
                "is_plural": True,
                "main_video_embed": None,
                "main_video_url": None,
                "name": "BeastBeat",
                "one_liner": None,
                "outstanding_payment_amount_cents": 0,
                "paid_member_count": 1694,
                "patron_count": 14764,
                "pay_per_name": "month",
                "pledge_sum_currency": "USD",
                "pledge_url": "https://www.patreon.com/checkout/BeastBeatGame",
                "published_at": "2019-08-19T06:07:32.000+00:00",
                "should_display_chat_tab": False,
                "summary": '<p style=""><img src="https://c10.patreonusercontent.com/4/patreon-media/p/campaign/3067357/725acfca54794d78b4fa752a05eff5fa/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/36.png?token-time=1691107200&amp;token-hash=k6vkQnbi9q1rTRvA_Ywgdx6unwtrB2-0EmgNTevCkiY%3D" title=""></p><h1 style="text-align:center;">FOLLOW THE <span style="color:#0B0B0B;">BEAT</span>, PUSH BEAST\'S RHYTHM HIT THE WILD CLIMAX!</h1><h3 style="text-align:center;"><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">🔞Adult Only</mark></span></strong></h3><p style="">Welcome to BeastBeat, a 2D interactive animated rhythm game based on the R18 [M/M] Furry theme, playable on Android &amp; IOS &amp; Mac &amp; PC platform</p><p style="text-align:center;"><img src="https://img.itch.zone/aW1nLzEyNzg2OTgzLnBuZw==/original/w3GHSs.png" title=""></p><p style=""></p><h2 style="text-align:center;"><span style="color:#000000;"><mark style="background-color:#ffffff;">⬩ </mark></span>VARIOUS THEMES &amp; FETISHES <span style="color:#000000;"><mark style="background-color:#ffffff;">⬩</mark></span></h2><p style="">You will shuttle between sexy identities in different time and space, whether it is a reckless brave who was level-drain by the devil, or an archaeological new ass who stepped into the trap of Anubis, lover, foe, doctor, we will keep updating!</p><p style=""></p><p style=""><img src="https://img.itch.zone/aW1nLzEyNzg4MTYyLnBuZw==/original/W6%2FGAs.png" title=""></p><p style="text-align:center;"><img src="https://img.itch.zone/aW1nLzEyNzg4MTY0LmdpZg==/original/bkBZk0.gif" title=""><img src="https://img.itch.zone/aW1nLzEyNzg4MTY4LnBuZw==/original/w9eSVp.png" title=""></p><p style=""></p><h2 style="text-align:center;"><span style="color:#000000;"><mark style="background-color:#ffffff;">⬩ </mark></span>FULL LIVE2D ANIMATION <span style="color:#000000;"><mark style="background-color:#ffffff;">⬩</mark></span></h2><p style="">Interact and flirt with beast husband in the gallery with your mouse.</p><p style=""><span style="color:#0b0b0b;"><mark style="background-color:#ffffff;">The combination of 2D interactive animation and the theme of each mainstream sexual fetish will bring you an unprecedented experience</mark></span></p><p style=""></p><p style=""><img src="https://img.itch.zone/aW1nLzEyNzg4MTU1LnBuZw==/original/Szu2w5.png" title=""></p><p style="text-align:center;"><img src="https://img.itch.zone/aW1nLzEyNzg4MTQ5LmdpZg==/original/%2FKH3ZO.gif" title=""></p><p style=""><img src="https://img.itch.zone/aW1nLzEyNzg4MTY4LnBuZw==/original/w9eSVp.png" title=""></p><p style=""></p><h1 style="text-align:center;"><span style="color:#000000;"><mark style="background-color:#ffffff;">⬩ </mark></span><strong>GAME COMMUNITY</strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> ⬩</mark></span></h1><p style=""><img src="https://img.itch.zone/aW1nLzEyNzg2OTU0LnBuZw==/original/eug46K.png" title=""></p><h1 style="text-align:center;"><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">⬩ &nbsp;</mark></span></strong><a href="https://discord.gg/HdDCuSscpg" rel="noopener noreferrer nofollow" target="_blank">Discord</a><span style="color:#000000;"><mark style="background-color:#ffffff;">&nbsp; ⬩&nbsp; &nbsp;</mark></span><a href="https://www.patreon.com/BeastBeatGame" rel="noopener noreferrer nofollow" target="_blank">Patreon</a><span style="color:#000000;"><mark style="background-color:#ffffff;">&nbsp; ⬩&nbsp;&nbsp;</mark></span><a href="https://twitter.com/CBoneGames" rel="noopener noreferrer nofollow" target="_blank">Twitter</a><span style="color:#000000;"><mark style="background-color:#ffffff;">&nbsp;⬩</mark></span></h1><p style="text-align:start;line-height:1.4;"></p><p style="text-align:start;line-height:1.4;"><span style="color:#000000;"><mark style="background-color:#ffffff;">please report any bugs or comments through the Community session or the Discord server!&nbsp;</mark></span></p><p style="text-align:start;line-height:1.4;">If you are interested and want your song in the game, please submit your song on our discord server.</p><p style="">You can also get information about the latest game updates and activities on our social media and Discord server</p><p style=""></p><p style="text-align:center;line-height:1.4;"><img src="https://img.itch.zone/aW1nLzEyNzg2OTI0LnBuZw==/original/HhnGB6.png" title=""></p><ul><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">More than 10 sets of CG animation and songs</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> - With some original songs composed by various artists.</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">3 different difficulties</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> - Easy, Normal and Hell (multi-fingers required!) Are you ready to accept the challenge?</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Play just like any classic&nbsp;rhythm game</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> - Hit the notes on 4 lanes according to the beat!</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Interactive animation gallery mode</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> - Play with the character you like using your mouse!&nbsp;&nbsp;</mark></span><em><span style="color:#000000;"><mark style="background-color:#ffffff;">(Patreon exclusive)</mark></span></em></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Character CG backstory video</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> - Know more about the character you love.&nbsp; </mark></span><em><span style="color:#000000;"><mark style="background-color:#ffffff;">(Patreon exclusive)</mark></span></em></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Mobile version</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> - Play anywhere you go!&nbsp;&nbsp;</mark></span><em><span style="color:#000000;"><mark style="background-color:#ffffff;">(Patreon exclusive)</mark></span></em></p></li></ul><p style=""><img src="https://img.itch.zone/aW1nLzEyNzg2OTIwLnBuZw==/original/WzAaGD.png" title=""></p><ul><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">4Key rhythm game with multiple difficulty gradients</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;">-The classic 4Key audio game mode, you can challenge with various difficulties, from simple to difficult, enjoy the pleasure of breaking through yourself</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Multiple exclusive debut music</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;">-We invited Ardolf as the music director of the game, and created a unique BeastBeat music experience under the contribution of this outstanding musician</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">2D full animation CG</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;">-We are committed to the technical research of 2DCG animation, and continue to explore more possibilities</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Auto Unlock Gallery</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;"> </mark></span><strong><em>(Patreon exclusive)</em></strong><span style="color:#000000;"><mark style="background-color:#ffffff;">-Even if you don\'t play BeastBeat\'s audio game, you can still unlock the gallery with any score (even 0 points), and simply use it as a 2D flash game with a variety of sexy theme CG!</mark></span></p></li><li><p style=""><strong><span style="color:#000000;"><mark style="background-color:#ffffff;">Continuous update</mark></span></strong><span style="color:#000000;"><mark style="background-color:#ffffff;">-Join the discord community, you can provide your own opinions, and you can also discuss and exchange with other players and developers</mark></span></p></li></ul><p style="text-align:center;"><span style="color:#000000;"><mark style="background-color:#ffffff;">⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩⬩</mark></span></p><p style=""></p><p style=""><img src="https://img.itch.zone/aW1nLzEyNzg3MDA2LnBuZw==/original/pFzoq6.png" title=""></p><p style=""></p>',
                "thanks_embed": None,
                "thanks_msg": '<p style="">Thanks for your support!</p><p style="">C-BoneGames team will be able to create more furry games because of your love!</p>',
                "thanks_video_url": None,
                "url": "https://www.patreon.com/BeastBeatGame",
            },
            "relationships": {
                "creator": {
                    "data": {"id": "17223600", "type": "user"},
                    "links": {"related": "https://www.patreon.com/api/user/17223600"},
                },
                "goals": {"data": None},
                "rewards": {
                    "data": [
                        {"id": "-1", "type": "reward"},
                        {"id": "10306210", "type": "reward"},
                        {"id": "7264767", "type": "reward"},
                        {"id": "3914618", "type": "reward"},
                        {"id": "7264771", "type": "reward"},
                        {"id": "10053906", "type": "reward"},
                    ]
                },
            },
        },
        {
            "id": "15392640",
            "type": "campaign",
            "attributes": {
                "avatar_photo_image_urls": {
                    "original": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJxIjoxMDAsIndlYnAiOjB9/1.jpg?token-hash=6PKRz8SjPLx0dCCWHg9wqFV9TNyKL68jr80CKsJZumc%3D&token-time=1782000000",
                    "default": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJ3Ijo2MjB9/1.jpg?token-hash=TkhiaxNDb07mKp9IX6LXXZkAvcgx9ihf35tZc2sL1ek%3D&token-time=1782000000",
                    "default_small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJ3IjozNjB9/1.jpg?token-hash=7-BhdrTMhLlFeyubyaXMlha11kF-pvRR02pAIKGWaPw%3D&token-time=1782000000",
                    "default_large": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJ3IjoxMDgwfQ%3D%3D/1.jpg?token-hash=MbZn9nqLMA4lYLVY-uYZBbl0aBOKukMXsNpkvB96mFQ%3D&token-time=1782000000",
                    "default_blurred": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJiIjoyMCwidyI6NjIwfQ%3D%3D/1.jpg?token-hash=9ZkpwdUynClGn7Ea3udWK3T4qo_4-EwBRs3tlGMAl3g%3D&token-time=1782000000",
                    "default_blurred_small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJiIjoyMCwidyI6MzYwfQ%3D%3D/1.jpg?token-hash=TdZtH3FS6fg59xesvw2tVXbZiWVYDniWrUpd-SkJ7no%3D&token-time=1782000000",
                    "thumbnail": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJoIjozNjAsInciOjM2MH0%3D/1.jpg?token-hash=Xk0b3bGJX2p24E1cWA1jsFmw4OPgGxkNyAd_yruWmGw%3D&token-time=1782000000",
                    "thumbnail_large": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJoIjoxMDgwLCJ3IjoxMDgwfQ%3D%3D/1.jpg?token-hash=VP468rIGIk9LCSb0NiZZVgHZDN5NU8JYvB0i-et5fuc%3D&token-time=1782000000",
                    "thumbnail_small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJoIjoxMDAsInciOjEwMH0%3D/1.jpg?token-hash=2-gydex3Z05wEZoJMHzXeGXuZNgCO_1VFRiQQVk1Sbc%3D&token-time=1782000000",
                },
                "avatar_photo_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/d7d9443da7d147b2a73943b4837cad4a/eyJ3Ijo2MjB9/1.jpg?token-hash=_61LxoIBuVhCwRjO6FnbHqE1gyHPWdlITivpwiVWPD0%3D",
                "campaign_pledge_sum": 0,
                "cover_photo_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/1?token-hash=TasHYb2PQAjgTqoWBlSLdvIR55TFDP_mF_hJQi3mJAE%3D&token-time=1783123200",
                "cover_photo_url_sizes": {
                    "xsmall": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3Ijo2MjAsIndlIjoxfQ%3D%3D/1?token-hash=G0v4g1RgvEQ0Ooz7-1MCFVdEPa9SjZM-6EZroumrBGk%3D&token-time=1783123200",
                    "small": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3Ijo5NjAsIndlIjoxfQ%3D%3D/1?token-hash=oUNMug0qsDKB1NaHFIFL6488qhYmdT-Y76U6nn1_LXI%3D&token-time=1783123200",
                    "medium": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3IjoxMjAwLCJ3ZSI6MX0%3D/1?token-hash=aPFIciulwJ_4FwYQytJ9aFuaWm3QlG9urmWMCrL6l5M%3D&token-time=1783123200",
                    "large": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3IjoxNjAwLCJ3ZSI6MX0%3D/1?token-hash=tp684CrTJeQ9rn4uzFrx245hNWU0CyyrH2WOJam3n04%3D&token-time=1783123200",
                    "xlarge": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/1?token-hash=TasHYb2PQAjgTqoWBlSLdvIR55TFDP_mF_hJQi3mJAE%3D&token-time=1783123200",
                    "low_quality": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJiIjo1MCwicSI6MSwidyI6NjIwLCJ3ZSI6MX0%3D/1?token-hash=ETlhLizQqc9Z-Cos1bZTSWO7aDOzNh4JJVHsu2SrSwU%3D&token-time=1783123200",
                },
                "created_at": "2026-01-11T07:04:57.000+00:00",
                "creation_count": 0,
                "creation_name": None,
                "currency": "USD",
                "discord_server_id": None,
                "display_patron_goals": False,
                "earnings_visibility": "public",
                "image_small_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/1?token-hash=TasHYb2PQAjgTqoWBlSLdvIR55TFDP_mF_hJQi3mJAE%3D&token-time=1783123200",
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/campaign/15392640/f147ee5f4ebb4a70802ea96ab396eb0d/eyJ3IjoxOTIwLCJ3ZSI6MX0%3D/1?token-hash=TasHYb2PQAjgTqoWBlSLdvIR55TFDP_mF_hJQi3mJAE%3D&token-time=1783123200",
                "is_charge_upfront": True,
                "is_charged_immediately": True,
                "is_monthly": True,
                "is_new_fandom": False,
                "is_nsfw": False,
                "is_plural": False,
                "main_video_embed": None,
                "main_video_url": None,
                "name": "陨落基围虾",
                "one_liner": None,
                "outstanding_payment_amount_cents": 0,
                "paid_member_count": 0,
                "patron_count": 0,
                "pay_per_name": "month",
                "pledge_sum": 0,
                "pledge_sum_currency": "USD",
                "pledge_url": "https://www.patreon.com/checkout/falling_shrimp",
                "published_at": None,
                "should_display_chat_tab": False,
                "summary": None,
                "thanks_embed": None,
                "thanks_msg": None,
                "thanks_video_url": None,
                "url": "https://www.patreon.com/user?u=181945268",
            },
            "relationships": {
                "creator": {
                    "data": {"id": "181945268", "type": "user"},
                    "links": {"related": "https://www.patreon.com/api/user/181945268"},
                },
                "goals": {"data": None},
                "rewards": {
                    "data": [
                        {"id": "-1", "type": "reward"},
                        {"id": "27686419", "type": "reward"},
                    ]
                },
            },
        },
        {
            "id": "-1",
            "type": "reward",
            "attributes": {
                "amount": 0,
                "amount_cents": 0,
                "description": "Everyone",
                "user_limit": None,
                "remaining": 0,
                "requires_shipping": False,
                "created_at": None,
                "url": None,
                "patron_currency": "USD",
            },
        },
        {
            "id": "10306210",
            "type": "reward",
            "attributes": {
                "amount": 0,
                "amount_cents": 0,
                "created_at": "2023-10-11T19:31:04.325+00:00",
                "currency": "USD",
                "declined_patron_count": 138,
                "description": "",
                "discord_role_ids": None,
                "edited_at": "2023-10-11T19:31:04.325+00:00",
                "image_url": None,
                "is_free_tier": True,
                "patron_amount_cents": 0,
                "patron_currency": "USD",
                "post_count": 2,
                "published": True,
                "published_at": "2023-10-11T19:31:04.325+00:00",
                "remaining": None,
                "requires_shipping": False,
                "title": "Free",
                "unpublished_at": None,
                "url": "https://www.patreon.com/checkout/BeastBeatGame?rid=10306210",
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "3067357", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/3067357"
                    },
                }
            },
        },
        {
            "id": "3914618",
            "type": "reward",
            "attributes": {
                "amount": 500,
                "amount_cents": 500,
                "created_at": "2019-08-17T13:35:56.759+00:00",
                "currency": "USD",
                "declined_patron_count": 48,
                "description": "<ul><li><p>Project preview</p></li><li><p><strong>Chance to vote</strong></p></li><li><p><strong>Name signed thanks in-game</strong></p></li></ul><p><strong>                        <u>[BeastBeat]</u></strong></p><ul><li><p>[A]Get Patreon_Build version game</p></li><li><p><strong>[B]CG-Pic-pack [Partial]</strong></p></li></ul>",
                "discord_role_ids": ["1128899792832045056"],
                "edited_at": "2023-07-12T10:33:31.808+00:00",
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/reward/3914618/ee56852d7db64038af03c0f7f169f0fa/eyJ3Ijo0MDB9/6.png?token-hash=FQOLmlQVS9P7xER_d_rUj6dWmLxnnhGnT14IvVTr6To%3D",
                "is_free_tier": False,
                "patron_amount_cents": 500,
                "patron_currency": "USD",
                "post_count": 91,
                "published": True,
                "published_at": "2021-12-31T14:23:45.968+00:00",
                "remaining": None,
                "requires_shipping": False,
                "title": "Magic flow",
                "unpublished_at": None,
                "url": "https://www.patreon.com/checkout/BeastBeatGame?rid=3914618",
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "3067357", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/3067357"
                    },
                }
            },
        },
        {
            "id": "7264771",
            "type": "reward",
            "attributes": {
                "amount": 1000,
                "amount_cents": 1000,
                "created_at": "2021-05-30T08:11:18.214+00:00",
                "currency": "USD",
                "declined_patron_count": 44,
                "description": "<ul><li><p>Project preview</p></li><li><p>Chance to vote</p></li><li><p>Name signed thanks in-game</p></li></ul><p><strong>                       <u>[BeastBeat]</u></strong></p><ul><li><p>[A]Get Patreon_Build version game</p></li><li><p><strong>[B]CG-Pic-pack [Full]</strong></p></li><li><p><strong>[C]CG-Animation Video</strong></p></li></ul>",
                "discord_role_ids": ["1128899792832045056"],
                "edited_at": "2023-07-12T10:33:47.652+00:00",
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/reward/7264771/9c57eabaa7c94ca5a9762687e72a92e8/eyJ3Ijo0MDB9/2.png?token-hash=0g4EgcbulK-UE0zslInNeEXjXYqpQFgOHfmRaa8r-is%3D",
                "is_free_tier": False,
                "patron_amount_cents": 1000,
                "patron_currency": "USD",
                "post_count": 134,
                "published": True,
                "published_at": "2021-12-31T14:23:54.207+00:00",
                "remaining": None,
                "requires_shipping": False,
                "title": "Magic pond",
                "unpublished_at": None,
                "url": "https://www.patreon.com/checkout/BeastBeatGame?rid=7264771",
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "3067357", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/3067357"
                    },
                }
            },
        },
        {
            "id": "10053906",
            "type": "reward",
            "attributes": {
                "amount": 1300,
                "amount_cents": 1300,
                "created_at": "2023-08-04T01:21:57.988+00:00",
                "currency": "USD",
                "declined_patron_count": 9,
                "description": '<p style=""><strong><span style="color:rgb(17, 17, 17);"><mark style="background-color:rgb(255, 255, 255);">💿</mark></span>Contains all rewards from previous tiers!!!</strong></p><p style=""><strong>+mp3 OST Game music award </strong></p><p style="">+for each sponsor who chooses this tier, all the extra income compared with the previous tier will be provided to the musician to support his music creation</p>',
                "discord_role_ids": ["1128899792832045056"],
                "edited_at": "2023-08-04T02:40:01.598+00:00",
                "image_url": "https://c10.patreonusercontent.com/4/patreon-media/p/reward/10053906/026134e944a04be2b0d400628f011c4c/eyJ3Ijo0MDB9/1.png?token-hash=_8ozl7iHlCYNCK1omontmWrPnc8m9TGesZMbWiYoYsI%3D",
                "is_free_tier": False,
                "patron_amount_cents": 1300,
                "patron_currency": "USD",
                "post_count": 152,
                "published": True,
                "published_at": "2023-08-04T01:21:57.988+00:00",
                "remaining": None,
                "requires_shipping": False,
                "title": "Desire bursting",
                "unpublished_at": None,
                "url": "https://www.patreon.com/checkout/BeastBeatGame?rid=10053906",
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "3067357", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/3067357"
                    },
                }
            },
        },
        {
            "id": "27686419",
            "type": "reward",
            "attributes": {
                "amount": 0,
                "amount_cents": 0,
                "created_at": "2026-01-11T07:04:58.235+00:00",
                "currency": "USD",
                "declined_patron_count": 0,
                "description": "",
                "discord_role_ids": None,
                "edited_at": "2026-01-11T07:04:58.235+00:00",
                "image_url": None,
                "is_free_tier": True,
                "patron_amount_cents": 0,
                "patron_count": 0,
                "patron_currency": "USD",
                "post_count": 0,
                "published": True,
                "published_at": "2026-01-11T07:04:58.235+00:00",
                "remaining": None,
                "requires_shipping": False,
                "title": "Free",
                "unpublished_at": None,
                "url": "https://www.patreon.com/checkout/falling_shrimp?rid=27686419",
                "user_limit": None,
                "welcome_message": None,
                "welcome_message_unsafe": None,
                "welcome_video_embed": None,
                "welcome_video_url": None,
            },
            "relationships": {
                "campaign": {
                    "data": {"id": "15392640", "type": "campaign"},
                    "links": {
                        "related": "https://www.patreon.com/api/campaigns/15392640"
                    },
                }
            },
        },
    ],
}
